# Generated by Django 5.0.4 on 2024-04-18 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_leadmodel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.coursemanage'),
        ),
    ]
