# Generated by Django 5.0.4 on 2024-04-18 09:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_alter_leadmodel_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_title', models.CharField(max_length=80, unique=True)),
                ('sub_cat_status', models.BooleanField(default=False)),
                ('sub_cat_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=80)),
                ('chapter_image', models.ImageField(upload_to='')),
                ('chapter_logo', models.ImageField(upload_to='')),
                ('chapter_banner', models.ImageField(upload_to='')),
                ('chapter_description', models.TextField()),
                ('chapter_status', models.BooleanField(default=False)),
                ('chapter_date', models.DateTimeField(default=datetime.datetime.now)),
                ('course_title', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='console.course')),
                ('spec_title', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='console.specialization')),
                ('sub_cat_title', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='console.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='Create_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=80)),
                ('lesson_image', models.ImageField(upload_to='')),
                ('lesson_logo', models.ImageField(upload_to='')),
                ('lesson_banner', models.ImageField(upload_to='')),
                ('lesson_description', models.TextField()),
                ('lesson_status', models.BooleanField(default=False)),
                ('lesson_date', models.DateTimeField(default=datetime.datetime.now)),
                ('chapter_title', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='console.create_chapter')),
                ('course_title', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='console.course')),
                ('spec_title', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='console.specialization')),
                ('sub_cat_title', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='console.sub_category')),
            ],
        ),
    ]
