# Generated by Django 5.0.4 on 2024-04-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0016_sub_category_create_chapter_create_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='batch_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.regulations'),
        ),
        migrations.AlterField(
            model_name='coursemanage',
            name='teaching_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.employee_model'),
        ),
    ]
