# Generated by Django 5.0.4 on 2024-04-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_leadmodel_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmodel',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_title',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=100),
        ),
    ]
