# Generated by Django 5.0.4 on 2024-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_remove_leadmodel_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
