# Generated by Django 5.0.4 on 2024-04-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0021_course_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_status',
            field=models.BooleanField(default=False),
        ),
    ]
