# Generated by Django 5.0.4 on 2024-04-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0022_alter_sub_category_sub_cat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_chapter',
            name='crn_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='console.register_model'),
        ),
        migrations.AlterField(
            model_name='create_chapter',
            name='chapter_image',
            field=models.ImageField(upload_to='chapter_image'),
        ),
        migrations.AlterField(
            model_name='create_chapter',
            name='chapter_logo',
            field=models.ImageField(upload_to='chapter_logo'),
        ),
    ]
