# Generated by Django 5.0.4 on 2024-04-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0023_create_chapter_crn_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_lesson',
            name='crn_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='console.register_model'),
        ),
        migrations.AlterField(
            model_name='create_chapter',
            name='chapter_status',
            field=models.BooleanField(default=True),
        ),
    ]
