# Generated by Django 5.0.4 on 2024-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0024_create_lesson_crn_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_lesson',
            name='lesson_banner',
        ),
        migrations.AlterField(
            model_name='create_lesson',
            name='lesson_image',
            field=models.ImageField(null=True, upload_to='lesson_image'),
        ),
        migrations.AlterField(
            model_name='create_lesson',
            name='lesson_logo',
            field=models.ImageField(null=True, upload_to='lesson_logo'),
        ),
    ]
