# Generated by Django 5.0.4 on 2024-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0026_leadmodel_faculty_alter_create_lesson_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upipayments',
            name='upi_qr_code',
            field=models.ImageField(blank=True, upload_to='upi_qr_code'),
        ),
    ]
