# Generated by Django 5.0.4 on 2024-04-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0029_create_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_topic',
            name='topic_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Finance_and_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(blank=True, choices=[('Received', 'Received'), ('Not Received', 'Not Received'), ('Mis Matched', 'Mis Matched'), ('Suspicious', 'Suspicious')], max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fince_password', models.CharField(blank=True, max_length=225, null=True)),
                ('crn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_and_accounts', to='console.register_model')),
                ('leadstage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='console.leadmodel')),
            ],
        ),
    ]
