# Generated by Django 5.0.4 on 2024-04-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0030_alter_create_topic_topic_status_finance_and_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
