# Generated by Django 5.0.4 on 2024-04-23 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0031_leadmodel_token_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 15, 21, 46, 75322)),
        ),
    ]
