# Generated by Django 5.0.4 on 2024-04-24 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0032_alter_leadmodel_token_generated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmodel',
            name='token_generated_date',
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='admission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 21, 15, 13, 764090)),
        ),
    ]
