# Generated by Django 5.0.4 on 2024-04-24 16:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0033_remove_leadmodel_token_generated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 22, 16, 40, 727213)),
        ),
        migrations.CreateModel(
            name='Student_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('crn_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment', to='console.register_model')),
                ('studend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.leadmodel')),
            ],
        ),
    ]
