# Generated by Django 5.0.4 on 2024-04-24 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0034_alter_leadmodel_token_generated_at_student_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_payment',
            name='mode_of_payment',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_payment',
            name='transaction_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 22, 19, 12, 734959)),
        ),
    ]
