# Generated by Django 5.0.4 on 2024-04-25 06:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0035_student_payment_mode_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_payment',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.coursemanage'),
        ),
        migrations.AddField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 12, 7, 27, 643189)),
        ),
        migrations.AddField(
            model_name='student_payment',
            name='net_banking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.netbanking'),
        ),
        migrations.AddField(
            model_name='student_payment',
            name='upi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.upipayments'),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 12, 7, 27, 643189)),
        ),
    ]
