# Generated by Django 5.0.4 on 2024-04-25 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0036_student_payment_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='messages_for_discount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='request_for_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 18, 6, 29, 784634)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 18, 6, 29, 784634)),
        ),
    ]
