# Generated by Django 5.0.4 on 2024-04-26 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0038_alter_leadmodel_token_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vendor',
            name='alternatemobile',
            field=models.CharField(default=8340047698, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 16, 39, 161844)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 16, 39, 180635)),
        ),
    ]
