# Generated by Django 5.0.4 on 2024-04-26 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0039_company_vendor_alternatemobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vendor',
            name='website',
            field=models.CharField(default='https://movie-mela-a95cb.web.app/', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 18, 54, 336306)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 18, 54, 337314)),
        ),
    ]
