# Generated by Django 5.0.4 on 2024-04-26 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0040_company_vendor_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 21, 29, 27, 176262)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 21, 29, 27, 178799)),
        ),
    ]
