# Generated by Django 5.0.1 on 2024-04-27 11:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0042_mail_student_leadmodel_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 17, 18, 56, 19935)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 17, 18, 56, 19935)),
        ),
        migrations.CreateModel(
            name='Job_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last_date_to_apply', models.DateField()),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.company_vendor')),
                ('crn_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='console.register_model')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.qualification')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.jobrole')),
            ],
        ),
    ]
