# Generated by Django 5.0.1 on 2024-04-27 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0043_alter_leadmodel_token_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 17, 28, 55, 824123)),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 17, 28, 55, 818126)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 17, 28, 55, 821123)),
        ),
    ]
