# Generated by Django 5.0.1 on 2024-04-27 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0044_job_post_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='job_description',
            field=models.TextField(default='kasjdfhljasha.nslkjsnkdljhfskzjvnklsjnlvkjsnlkjnlaskjdvnlkjanslkdn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 17, 55, 1, 914572)),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 17, 55, 1, 907155)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 17, 55, 1, 910180)),
        ),
    ]
