# Generated by Django 5.0.4 on 2024-04-28 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0045_job_post_job_description_alter_job_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 10, 52, 1, 492362)),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 10, 52, 1, 480961)),
        ),
        migrations.AlterField(
            model_name='student_payment',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 10, 52, 1, 480961)),
        ),
    ]
