# Generated by Django 5.0.4 on 2024-05-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0068_alter_company_and_employee_modal_payment_date_and_more'),
        ('student_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studen_credentials',
            new_name='StudentCredentials',
        ),
    ]
