# Generated by Django 5.0.4 on 2024-05-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0070_alter_company_and_employee_modal_payment_date_and_more'),
        ('student_panel', '0003_rename_studend_id_studentcredentials_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOneTimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('education_data', models.CharField(max_length=2000, null=True)),
                ('project_data', models.CharField(max_length=2000, null=True)),
                ('certification_data', models.CharField(max_length=2000, null=True)),
                ('Qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.qualification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.leadmodel')),
            ],
        ),
    ]
