# Generated by Django 5.0.4 on 2024-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_panel', '0004_studentonetimeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentonetimeprofile',
            name='permanent_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentonetimeprofile',
            name='permanent_country',
            field=models.CharField(default='address', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentonetimeprofile',
            name='permanent_state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
